version: '3'
services:
  nodeapp:
    container_name: nodeapp
    build: ./node
    ports:
      - "50002:50002"
    depends_on:
      - redis
      - placement
    networks:
      - hello-dapr
  nodeapp-dapr:
    container_name: nodeapp-dapr
    image: "daprio/daprd:edge"
    command: [ "./daprd",
               "-app-id", "nodeapp",
               "-app-port", "3000",
               "-placement-host-address", "placement:50006",
               "-components-path", "/components" ]
    volumes:
      - "./components/:/components"
    depends_on:
      - nodeapp
    network_mode: "service:nodeapp"
  pythonapp:
    container_name: pythonapp
    build: ./python
    depends_on:
      - redis
      - placement
    networks:
      - hello-dapr
  pythonapp-dapr:
    container_name: pythonapp-dapr
    image: "daprio/daprd:edge"
    command: [ "./daprd",
               "-app-id", "pythonapp",
               "-placement-host-address", "placement:50006",
               "-components-path", "/components" ]
    volumes:
      - "./components/:/components"
    depends_on:
      - pythonapp
    network_mode: "service:pythonapp"
  python-flask:
    container_name: python-flask
    build: ./python-flask
    depends_on:
      - redis
      - placement
    networks:
      - hello-dapr
  python-flask-dapr:
    container_name: python-flask-dapr
    image: "daprio/daprd:edge"
    command: [
        "./daprd",
        "-app-id", "python-flask",
        "-app-port", "5000",
        "-placement-host-address", "placement:50006",
        "-components-path", "/components"
    ]
    volumes:
      - "./components/:/components"
    depends_on:
      - pythonapp
    network_mode: "service:python-flask"
  placement:
    container_name: placement
    image: "daprio/dapr"
    command: [ "./placement", "-port", "50006" ]
    ports:
      - "50006:50006"
    networks:
      - hello-dapr
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - hello-dapr
networks:
  hello-dapr:
