kind: Service
apiVersion: v1
metadata:
  name: python-flask
  labels:
    app: python-flask
spec:
  selector:
    app: python-flask
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask
  labels:
    app: python-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-flask
  template:
    metadata:
      labels:
        app: python-flask
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "python-flask"
        dapr.io/app-port: "5000"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: python
        image: ghcr.io/wrysjy/python-flask:latest
      imagePullSecrets:
        - name: docker-registry-secret